# Site settings
language:               "en"
title:                  "Site Title"
description:            "Site description"
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - ".DS_Store"
  - "/assets/"
  - "DOC.md"
  - "Gemfile*"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "README.md"
  - "*.json"
  - "*.lock"
  - "*.log"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:          "/blog/:title/"
excerpt_separator:  "<!--more-->"
paginate_path:      "/blog/page:num"
paginate:           5

compress_html:
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [development]
